# travis.yml for zam-plugins uses 14.04 Ubuntu Trusty

os:
  - linux

sudo: required

dist: trusty

git:
  submodules: false

before_install:
  - sudo add-apt-repository ppa:kxstudio-debian/mingw -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository universe -y
  - sudo apt-get update -qq -y
  - sudo apt-get install wine1.6-amd64 wine1.6-i386 -y
  - wget http://ppa.launchpad.net/kxstudio-team/builds/ubuntu/pool/main/a/apple-macports-fftw-3/apple-macports-fftw-3_3.3.3-1_all.deb
  - wget http://ppa.launchpad.net/kxstudio-team/builds/ubuntu/pool/main/a/apple-macports-liblo/apple-macports-liblo_0.26-1_all.deb
  - wget http://ppa.launchpad.net/kxstudio-team/builds/ubuntu/pool/main/a/apple-x86-gcc/apple-x86-gcc_4.2.1~5646-1kxstudio2_amd64.deb
  - wget http://ppa.launchpad.net/kxstudio-team/builds/ubuntu/pool/main/a/apple-x86-odcctools/apple-x86-odcctools_758.159-0kxstudio2_amd64.deb
  - wget -c https://launchpad.net/~flosoft/+archive/ubuntu/cross-apple/+files/apple-uni-sdk-10.5_20110407-0.flosoft1_amd64.deb --no-check-certificate
  - wget http://ppa.launchpad.net/kxstudio-team/builds/ubuntu/pool/main/a/apple-x86-setup/apple-x86-setup_2_amd64.deb
  - sudo dpkg -i apple-x86-odcctools_758.159-0kxstudio2_amd64.deb
  - sudo dpkg -i apple-x86-gcc_4.2.1~5646-1kxstudio2_amd64.deb
  - sudo dpkg -i apple-uni-sdk-10.5_20110407-0.flosoft1_amd64.deb
  - sudo dpkg -i apple-x86-setup_2_amd64.deb
  - sudo dpkg -i apple-macports-liblo_0.26-1_all.deb
  - sudo dpkg -i apple-macports-fftw-3_3.3.3-1_all.deb
  - sudo apt-get install mingw64-x-gcc -y
  - sudo apt-get install mingw64-x-binutils -y
  - sudo apt-get install mingw64-x-pkgconfig -y
  - sudo apt-get install mingw64-x-liblo -y
  - sudo apt-get install mingw64-x-fftw3 -y
  - sudo apt-get install mingw64-x-libsndfile -y
  - sudo apt-get install g++-4.8 -y
  - sudo apt-get install binutils -y
  - sudo apt-get install pkg-config -y
  - sudo apt-get install libx11-dev -y
  - sudo apt-get install libgl1-mesa-dev -y
  - sudo apt-get install liblo-dev -y
  - sudo apt-get install fftw3-dev -y
  - sudo apt-get install libsndfile-dev -y
  - sudo apt-get install libjack-dev -y
  - sudo apt-get install ladspa-sdk -y

cache:
  - apt

script:
  - export ZAMVERSION=$(git describe)
  - rm -fr dpf
  - git clone https://github.com/zamaudio/DPF dpf
  - cd dpf
  - git checkout build-osxwin
  - cd ..
  - export CC=gcc
  - export CXX=g++-4.8
  - export AR=ar
  - make LINUX=true -j2
  - mv bin linux
  - mkdir bin
  - export CC=i686-apple-darwin10-gcc
  - export CXX=i686-apple-darwin10-g++
  - export AR=i686-apple-darwin10-ar
  - make clean
  - make MACOS=true MACOS_OLD=true -j2
  - mv bin osx
  - mkdir bin
  - export PATH=$PATH:/opt/mingw64/bin
  - export CXXFLAGS="-I/opt/mingw64/x86_64-w64-mingw32/include -I/opt/mingw64/include"
  - export CFLAGS="-I/opt/mingw64/x86_64-w64-mingw32/include -I/opt/mingw64/include"
  - export CC=x86_64-w64-mingw32-gcc
  - export CXX=x86_64-w64-mingw32-g++
  - export AR=x86_64-w64-mingw32-ar
  - make clean
  - rm -fr ~/.wine
  - make WIN32=true -j2
  - mv bin win32
  - mkdir bin
  - make clean
  - rm -fr ~/.wine
  - make WIN64=true -j2
  - mv bin win64
  - mkdir bin
  - cd win64
  - for f in *.lv2; do cd $f; cp *.ttl ../../osx/$f/ ; cd .. ; done
  - cd ../osx
  - for f in *.lv2; do cd $f; perl -pi -e 's/dll/dylib/g' manifest.ttl; perl -pi -e 's/WindowsUI/CocoaUI/g' manifest.ttl; cd .. ; done
  - cd ../linux
  - zip -9 -r zam-plugins-$ZAMVERSION-linuxlv2.zip *.lv2
  - mv *.zip ../bin
  - cd ../osx
  - zip -9 -r zam-plugins-$ZAMVERSION-osxlv2.zip *.lv2
  - mv *.zip ../bin
  - cd ../win32
  - zip -9 -r zam-plugins-$ZAMVERSION-win32lv2.zip *.lv2
  - mv *.zip ../bin
  - cd ../win64
  - zip -9 -r zam-plugins-$ZAMVERSION-win64lv2.zip *.lv2
  - mv *.zip ../bin
  - cd ../bin
  - echo "ALL DONE!!!"

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file:
#    - zam-plugins-$ZAMVERSION-linuxlv2.zip
#    - zam-plugins-$ZAMVERSION-osxlv2.zip
#    - zam-plugins-$ZAMVERSION-win32lv2.zip
#    - zam-plugins-$ZAMVERSION-win64lv2.zip
#  skip_cleanup: true
#  on:
#    tags: true
